/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/DYbdigHSBVl
 */
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar";
import {
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useRouter } from "next/router";

export function UserCard({ role, userList }) {
  const router = useRouter();
  return (
    <div className="max-w-md mx-auto bg-white rounded-xl shadow-md overflow-hidden md:max-w-2xl">
      <Card className="m-4">
        <CardHeader className="flex items-center gap-3">
          <Avatar className="h-16 w-16">
            <AvatarImage
              alt="User Profile Picture"
              src="/placeholder-avatar.jpg"
            />
            <AvatarFallback>JP</AvatarFallback>
          </Avatar>
          <div className="grid gap-1 text-sm">
            <div className="font-medium text-lg">{data.name}</div>
            <a className="text-blue-500 hover:underline" href="#">
              {data.email}
            </a>
          </div>
        </CardHeader>
        <CardContent>
          <div className="grid gap-1 text-sm">
            <div>
              <strong>Address:</strong> {data.address}
            </div>
            <div>
              <strong>Phone:</strong> {data.phone}
            </div>
            <div>
              <strong>Department:</strong> {data.department_name}
            </div>
          </div>
        </CardContent>
        <CardFooter className="flex justify-between">
          <Badge className="items-center" variant="outline">
            <UserIcon className="h-3.5 w-3.5 -translate-x-1" />
            {data.department_name}
          </Badge>
          <Button
            size="sm"
            onClick={() => {
              router.push(
                `manager/${
                  role == "doctor"
                    ? "doctor-management"
                    : role == "nurse"
                    ? "nurse-management"
                    : role == "patient"
                    ? "patient-management"
                    : "doctor-management"
                }/update/${data.role_id}`
              );
            }}
          >
            Edit Profile
          </Button>
        </CardFooter>
      </Card>
    </div>
  );
}

function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  );
}
